name: "Docker"

on:
  workflow_call:
    inputs:
      docker-push:
        required: false
        default: false
        description: "Enable docker push"
        type: boolean
      platforms:
        required: false
        default: "linux/amd64,linux/arm64"
        description: "Comma separated list of platforms for docker buildx"
        type: string
    secrets:
      DOCKER_GITHUB_TOKEN:
        required: true

jobs:
  docker:
    name: "Docker"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

    - name: Make Docker
      if: ${{ ! inputs.docker-push }}
      run: make docker

    - name: Make Docker Push
      if: ${{ inputs.docker-push }}
      run: make docker-push
