name: "Unit Test"

on:
  workflow_call:
    inputs:
      enable-codecov:
        required: false
        default: false
        description: "Enable codecov reports"
        type: boolean
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Go Cache
      if: ${{ hashFiles('go.mod') != '' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          artifacts/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      if: ${{ hashFiles('go.mod') != '' }}
      uses: actions/setup-go@v5
      with:
        go-version: ^1
      id: go

    - name: Set up go env
      run: export PATH=${PATH}:`go env GOPATH`/bin

    - name: Run golangci/golangci-lint
      if: ${{ hashFiles('go.mod') != '' }}
      uses: golangci/golangci-lint-action@v6
      with:
        skip-cache: true
        version: latest

    - name: Run Unit Tests Target
      if: ${{ hashFiles('Makefile') != '' }}
      run: make test

    - name: Run CI Target
      if: ${{ hashFiles('Makefile') != '' }}
      run: make ci

    - name: Run Mage
      if: ${{ hashFiles('magefiles/*') != '' }}
      uses: magefile/mage-action@v3
      with:
        version: latest

    - name: Publish Unit Test Coverage
      if: ${{ inputs.enable-codecov }}
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
