name: "Unit Test"

on:
  workflow_call:
    inputs:
      enable-codecov:
        required: false
        default: false
        description: "Enable codecov reports"
        type: boolean
    secrets:
      codecov_token:
        required: false

jobs:
  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Go Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          artifacts/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1
      id: go

    - name: Set up go env
      run: export PATH=${PATH}:`go env GOPATH`/bin

    - name: Run golangci/golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-cache: true
        version: latest

    - name: Run Unit Tests Target
      run: make test

    - name: Run CI Target
      run: make ci

    - name: Publish Unit Test Coverage
      if: ${{ inputs.enable-codecov }}
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
